version: '3.5'

services:
  redis:
    container_name: cloudprnt-redis
    image: redis
    ports:
      - '6379:6379'
  fastify-cloudprnt:
    container_name: fastify-cloudprnt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
    depends_on:
      - redis
    command: "npm run example:redis:start"
